title: Nikhil Bafna
email: zodvik@gmail.com
baseurl: ""
url: "https://zodvik.com"
twitter_username: zodvik
github_username:  zodvik
markdown: redcarpet
permalink: /posts/:title

collections:
  purchases:
    output: true
    permalink: /:collection/:title
  drafts:
    output: false

